<?
$PERM["index.php"]["G5"]="W";
$PERM["index.php"]["*"]="D";
$PERM["index.php"]["AU"]="R";
$PERM["news.php"]["AU"]="R";
$PERM["news.php"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["about"]["5"]="W";
$PERM["/"]["*"]="R";
?>